POST http://localhost:3000/register/
Content-Type: application/json

{
    "first_name": "Sardhaar vallabhai",
    "last_name": "Patel",
    "email": "sardhaar@sasi.ac.in",
    "register": "Polo 1",
    "password": "Sardhaar@123",
    "type": "Student"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "email": "trump@sasi.ac.in",
    "password": "Trump@123" 
}

###

GET http://localhost:3000/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRydW1wQHNhc2kuYWMuaW4iLCJyZWdObyI6IjIySzYxNDQ2OSIsInR5cGUiOiJTdHVkZW50IiwiaWF0IjoxNzQyODE5NTQ3fQ.4UbalO3pazL75MeEW_thX_bq4srViNkFYXly23wPC8Q

###

GET http://localhost:3000/complaints/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRydW1wQHNhc2kuYWMuaW4iLCJyZWdObyI6IjIySzYxNDQ2OSIsInR5cGUiOiJTdHVkZW50IiwiaWF0IjoxNzQyODEyMzc5fQ.jgICR_p_eLSL_XOMzrHGy0rYxDqjK3eJbrz8hz0NGzA

###

POST http://localhost:3000/complaints/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRydW1wQHNhc2kuYWMuaW4iLCJyZWdObyI6IjIySzYxNDQ2OSIsInR5cGUiOiJTdHVkZW50IiwiaWF0IjoxNzQyODEyMzc5fQ.jgICR_p_eLSL_XOMzrHGy0rYxDqjK3eJbrz8hz0NGzA
Content-Type: application/json

{
  "department": "Data Science",
  "title": "Harsha is too bad ",
  "description": "Tooooooooooo worest",
  "time_and_date": "2025-03-24 13:30:00",
  "status": 0,
  "filename": "voltage_report.pdf",
  "filetype": "application/pdf",
  "filesize": "750KB",
  "filedata": "base64_encoded_file_data",
  "email": "trump@sasi.ac.in"
}

###

PUT http://localhost:3000/complaints/20/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRydW1wQHNhc2kuYWMuaW4iLCJyZWdObyI6IjIySzYxNDQ2OSIsInR5cGUiOiJTdHVkZW50IiwiaWF0IjoxNzQyODE5NTQ3fQ.4UbalO3pazL75MeEW_thX_bq4srViNkFYXly23wPC8Q
